### ISSUE TITLE
Summary 

### ISSUE THREAD

**Issue by thecodeduchess** [kiranali/tea-cozy-website#6]
**Grade: Meets Expectations**    

**Summary:** This was a great implementation of the project. First, I test your project by downloading it and viewing it in my own browser. Next, I go step by step with your page against the requirements.  It matches with the required specs. After nitpicking through it, I did not find anything that requires a re-do. What I check for is code quality and how closely you can match to the spec. 

The code was easily readable and met the required styling, class and ID naming. If you want to build onto this project or future projects, you could consider adding a border on some of the elements, changing the font design, background color or use other various font colors. Don't be afraid to experiment a little bit. :)  That is allowed as long as you are following the general structure/page layout for practice. 

I hope you are enjoying your learning experience. You are certainly ready to move on to the next step!

**Comment by kiranali** [comment]
Thanks a lot for the feedback. Yes I need to experiment with the different design options as at the moment I am just following along the guidelines :smiley_cat:  

I used to be a .NET developer ( back-end) so all this design thing is very new and difficult for me but I am finally enjoying it. Let's see where this journey ends.!

**Comment by thecodeduchess** [comment]
I’m more backend too. Kinda hate design lol! But it’s something I’m working
on.




-- 
*Tell me and I forget. Show me and I remember. Involve me and I
understand. *

**Comment by kiranali** [comment]
Lol..well thank God someone else hates design too. This whole front-end html makes me feel so stupid but this year I have decided that I am going to conquer my fear of pixels once and for all.  Just need to practice till it becomes a habit.
